from amsa.algebra import Algebra

# Register the NumPy IR backend as the default execution engine.
from amsa.backends.numpy import NumpyBackend
from amsa.ir import register_backend
from amsa.layouts import MVLayout
from amsa.mv import MVArray
from amsa.ops import (
    add,
    anticommutator_product,
    bulk,
    bulk_dual,
    bulk_norm,
    bulk_norm_squared,
    bulk_normalize,
    commutator_product,
    conjugate,
    divide,
    dual,
    exp,
    geometric_product,
    inner_product,
    inverse,
    involute,
    left_contraction,
    motor_exp,
    motor_log,
    neg,
    norm,
    norm_squared,
    normalize,
    outer_product,
    poincare_dual,
    poincare_undual,
    project_grades,
    regressive_product,
    reverse,
    right_contraction,
    rigid_body_normalize,
    sandwich,
    scalar_product,
    sub,
    undual,
    unitize,
    weight,
    weight_dual,
    weight_norm,
    weight_norm_squared,
)
from amsa.specs import AlgebraSpec, grade_of_blade, pga2d, pga3d, vga, vga2d, vga3d

register_backend("numpy", NumpyBackend())

__all__ = [
    "Algebra",
    "AlgebraSpec",
    "MVArray",
    "MVLayout",
    "add",
    "anticommutator_product",
    "bulk",
    "bulk_dual",
    "bulk_norm",
    "bulk_norm_squared",
    "bulk_normalize",
    "commutator_product",
    "conjugate",
    "divide",
    "dual",
    "exp",
    "geometric_product",
    "grade_of_blade",
    "inner_product",
    "inverse",
    "involute",
    "left_contraction",
    "motor_exp",
    "motor_log",
    "neg",
    "norm",
    "norm_squared",
    "normalize",
    "outer_product",
    "pga2d",
    "pga3d",
    "poincare_dual",
    "poincare_undual",
    "project_grades",
    "regressive_product",
    "reverse",
    "rigid_body_normalize",
    "right_contraction",
    "sandwich",
    "scalar_product",
    "sub",
    "undual",
    "unitize",
    "vga",
    "vga2d",
    "vga3d",
    "weight",
    "weight_dual",
    "weight_norm",
    "weight_norm_squared",
]
